name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SERVER_SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

      - name: Deploy to Server
        run: |
          ssh -i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
          set -e
          git config --global --add safe.directory /home/boshadmin/PaymentTest
          cd /home/boshadmin

          if [ ! -d "PaymentTest/.git" ]; then
              rm -rf PaymentTest
              git clone https://github.com/IfodaAI/PaymentTest.git
          else
              cd PaymentTest
              git pull origin main
              cd ..
          fi

          cd PaymentTest

          if [ ! -d "base" ]; then
              python3 -m venv base
          fi

          source base/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt
          python manage.py makemigrations
          python manage.py migrate

          echo "$SUDO_PASSWORD" | sudo -S python manage.py runserver 0.0.0.0:8001
          EOF